gatinos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from .admin import admin_site
from django.urls import path, include

urlpatterns = [
    path('admin/', admin_site.urls),
    path('cuentas/', include('registration.urls', namespace="registration")),
    path('', include('gatos.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT,
                          show_indexes=True)

gatos/urls.py
from django.urls import path, include
from modernrpc.views import RPCEntryPoint
from . import views


gato_urls = [
    path('activity.png', views.GatoActivityPlotView.as_view(),
         name="gato-activity-graph"),
    path('actividades', views.ActividadesGato.as_view(),
         name="gato-activity"),
    path("capturar", views.CapturarGato.as_view(), name="capturar"),
    path("liberar", views.LiberarGato.as_view(), name="liberar"),
    path("morir", views.MorirGato.as_view(), name="morir"),
    path("capturas/c/<int:pk>", views.CapturaView.as_view(),
         name="captura"),
    path("capturas/c/<int:pk>/vacunar", views.VacunarGato.as_view(),
         name="vacunar"),
    path("capturas/c/<int:pk>/update", views.CapturaUpdateView.as_view(),
         name="captura-update"),
    path("capturas/c/<int:pk>/delete",
         views.CapturaDeleteView.as_view(),
         name="captura-delete"),
    path("enfermedad/create", views.EnfermedadCreateView.as_view(),
         name="enfermedad-create"),
    path("enfermedad/<int:pk>", views.EnfermedadView.as_view(),
         name="enfermedad"),
    path("enfermedad/e/<int:pk>/update", views.EnfermedadUpdateView.as_view(),
         name="enfermedad-update"),
    path("enfermedad/e/<int:pk>/delete", views.EnfermedadDeleteView.as_view(),
         name="enfermedad-delete"),
]


colonia_urls = [
    path('activity.png', views.ColoniaActivityPlotView.as_view(),
         name="colonia-activity-graph"),
    path('actividades', views.ActividadesColonia.as_view(),
         name="colonia-activity"),
    path('comidas', views.CalendarioComidas.as_view(),
         name="comidas"),
    path('avistamientos', views.Avistamientos.as_view(), name="avistamiento"),
    path('gatos/', views.GatosView.as_view(), name="gatos"),
    path('gato-add', views.GatoCreateView.as_view(), name="gato-add"),
    path('gatos/g/<slug:gato>', views.GatoView.as_view(), name="gato"),
    path('gatos/g/<slug:gato>/update', views.GatoUpdateView.as_view(),
         name="gato-update"),
    path('gatos/g/<slug:gato>/update', views.GatoUpdateView.as_view(),
         name="gato-update"),
    path('gatos/g/<slug:gato>/', include(gato_urls)),
    path('fotos/', views.FotosView.as_view(), name="fotos"),
    path('fotos/update-miniaturas', views.update_miniaturas,
         name="update-miniaturas"),
    path('fotos/update-exifs', views.update_exifs,
         name="update-exifs"),
    path('foto-add', views.FotoCreateView.as_view(), name="foto-add"),
    path('fotos/f/<str:foto>', views.FotoView.as_view(),
         name="foto"),
    path('fotos/f/<str:foto>/update', views.FotoUpdateView.as_view(),
         name="foto-update"),
    path('fotos/f/<str:foto>/delete', views.FotoDeleteView.as_view(),
         name="foto-delete"),
    path("informes", views.InformesView.as_view(),
         name="informes"),
    path("informes/create", views.InformeCreateView.as_view(),
         name="informe-create"),
    path("informes/i/<int:pk>", views.InformeView.as_view(),
         name="informe"),
    path("informes/i/<int:pk>/update", views.InformeUpdateView.as_view(),
         name="informe-update"),
    path("informes/i/<int:pk>/delete",
         views.InformeDeleteView.as_view(),
         name="informe-delete"),
    ]

user_urls = [
    path("activity.png", views.UserActivityPlotView.as_view()),
    ]

urlpatterns = [
    path("", views.ColoniasList.as_view(), name="colonias"),
    path("rpc/", RPCEntryPoint.as_view(enable_doc=True), name="RPC"),
    path('colonia-add', views.ColoniaCreateView.as_view(), name="colonia-add"),
    path('colonia/c/<slug:colonia>', views.ColoniaView.as_view(),
         name="colonia"),
    path('colonia/c/<slug:colonia>/update', views.ColoniaUpdateView.as_view(),
         name="colonia-update"),
    path('colonia/c/<slug:colonia>/', include(colonia_urls)),
    path('user/u/<str:username>/profile', views.UserProfile.as_view(),
         name="user-activity"),
    path('comidas/<str:codigo>', views.CalendarioComidas.as_view(),
         name="calendario-comidas"),
    ]

registration/urls.py
from django.urls import path, include
from . import views

app_name = "registration"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password_change/", views.PasswordChangeView.as_view(),
         name="password_change"),
    path("password_change_done/", views.PasswordChangeDoneView.as_view(),
         name="password_change_done"),
    ]

gatinos/forms.py
from django.forms.renderers import DjangoTemplates as DjangoTemplatesRenderer


class FormRenderer(DjangoTemplatesRenderer):
    form_template_name = "templates/forms/div.html"
    field_template_name = "templates/forms/field.html"

gatinos/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="description" content="" />
	<meta name="author" content="" />
	<meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width" />
    <title>{{ title }}</title>
    <link href="{% get_static_prefix %}css/reset.css" rel="stylesheet" />
    <link href="{% get_static_prefix %}css/gatos.css" rel="stylesheet" />
{% block base_head %}
{% endblock %}
</head>
<body>
  <header>
    <div class="main-header">
      <div class="main-header-left">
        <div id="titulo-aplicacion">
          <a href="{% url 'colonias' %}">{{ app_title }}</a> ({{ app_version }})
        </div>
      </div>
      <div class="main-header-right">

        {% if request.user.is_staff %}
          <a href="{% url "admin:index" %}">Admin</a> |
        {% endif %}
        {% if request.user.is_authenticated %}
        <a href="{% url "registration:password_change" %}">Cambiar contraseña</a>  |
        <a href="{% url "user-activity" username=request.user.username %}">Perfil</a>  |
        <a href="{% url "registration:logout" %}">Salir</a>
        {% elif not is_login %}
        <a href="{% url "registration:login" %}">Identificarse</a>
        {% endif %}

      </div>
    </div>
  </div>

  </header>
  {% for anuncio in anuncios %}
  <div class="anuncio anuncio-{{ anuncio.get_urgencia_display|lower }}">{{ anuncio.mensaje }}</div>
  {% endfor %}

  <main>
{% block base_body %}
{% endblock %}
  </main>
  <footer>
    &copy; {{ current_year }} Monforte Technologies
  </footer>
	<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
</body>

gatinos/templates/div.html
{{ errors }}
{% if errors and not fields %}
  <div>{% for field in hidden_fields %}{{ field }}{% endfor %}</div>
{% endif %}
{% for field, errors in fields %}
  <div{% with classes=field.css_classes %}{% if classes %} class="{{ classes }}"{% endif %}{% endwith %}>
    {{ field.as_field_group }}
    {% if forloop.last %}
      {% for field in hidden_fields %}{{ field }}{% endfor %}
    {% endif %}
</div>
{% endfor %}
{% if not fields and not errors %}
  {% for field in hidden_fields %}{{ field }}{% endfor %}
{% endif %}

gatinos/templates/field.html
{% if field.use_fieldset %}
  <fieldset{% if field.help_text and field.auto_id and "aria-describedby" not in field.field.widget.attrs %} aria-describedby="{{ field.auto_id }}_helptext"{% endif %}>
  {% if field.label %}{{ field.legend_tag }}{% endif %}
{% else %}
  {% if field.label %}{{ field.label_tag }}{% endif %}
{% endif %}
{% if field.help_text %}<div class="helptext"{% if field.auto_id %} id="{{ field.auto_id }}_helptext"{% endif %}>{{ field.help_text|safe }}</div>{% endif %}
{{ field.errors }}
{{ field }}{% if field.use_fieldset %}</fieldset>{% endif %}

gatinos/templates/label.html
{% if use_tag %}<{{ tag }}{% include 'django/forms/attrs.html' %}>{{ label }}</{{ tag }}>{% else %}{{ label }}{% endif %}