gatinos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from .admin import admin_site
from django.urls import path, include

urlpatterns = [
    path('admin/', admin_site.urls),
    path('cuentas/', include('registration.urls', namespace="registration")),
    path('', include('gatos.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT,
                          show_indexes=True)

gatos/urls.py
from django.urls import path, include
from modernrpc.views import RPCEntryPoint
from . import views


gato_urls = [
    path('activity.png', views.GatoActivityPlotView.as_view(),
         name="gato-activity-graph"),
    path('actividades', views.ActividadesGato.as_view(),
         name="gato-activity"),
    path("capturar", views.CapturarGato.as_view(), name="capturar"),
    path("liberar", views.LiberarGato.as_view(), name="liberar"),
    path("morir", views.MorirGato.as_view(), name="morir"),
    path("capturas/c/<int:pk>", views.CapturaView.as_view(),
         name="captura"),
    path("capturas/c/<int:pk>/vacunar", views.VacunarGato.as_view(),
         name="vacunar"),
    path("capturas/c/<int:pk>/update", views.CapturaUpdateView.as_view(),
         name="captura-update"),
    path("capturas/c/<int:pk>/delete",
         views.CapturaDeleteView.as_view(),
         name="captura-delete"),
    path("enfermedad/create", views.EnfermedadCreateView.as_view(),
         name="enfermedad-create"),
    path("enfermedad/<int:pk>", views.EnfermedadView.as_view(),
         name="enfermedad"),
    path("enfermedad/e/<int:pk>/update", views.EnfermedadUpdateView.as_view(),
         name="enfermedad-update"),
    path("enfermedad/e/<int:pk>/delete", views.EnfermedadDeleteView.as_view(),
         name="enfermedad-delete"),
]


colonia_urls = [
    path('activity.png', views.ColoniaActivityPlotView.as_view(),
         name="colonia-activity-graph"),
    path('actividades', views.ActividadesColonia.as_view(),
         name="colonia-activity"),
    path('comidas', views.CalendarioComidas.as_view(),
         name="comidas"),
    path('avistamientos', views.Avistamientos.as_view(), name="avistamiento"),
    path('gatos/', views.GatosView.as_view(), name="gatos"),
    path('gato-add', views.GatoCreateView.as_view(), name="gato-add"),
    path('gatos/g/<slug:gato>', views.GatoView.as_view(), name="gato"),
    path('gatos/g/<slug:gato>/update', views.GatoUpdateView.as_view(),
         name="gato-update"),
    path('gatos/g/<slug:gato>/update', views.GatoUpdateView.as_view(),
         name="gato-update"),
    path('gatos/g/<slug:gato>/', include(gato_urls)),
    path('fotos/', views.FotosView.as_view(), name="fotos"),
    path('fotos/update-miniaturas', views.update_miniaturas,
         name="update-miniaturas"),
    path('fotos/update-exifs', views.update_exifs,
         name="update-exifs"),
    path('foto-add', views.FotoCreateView.as_view(), name="foto-add"),
    path('fotos/f/<str:foto>', views.FotoView.as_view(),
         name="foto"),
    path('fotos/f/<str:foto>/update', views.FotoUpdateView.as_view(),
         name="foto-update"),
    path('fotos/f/<str:foto>/delete', views.FotoDeleteView.as_view(),
         name="foto-delete"),
    path("informes", views.InformesView.as_view(),
         name="informes"),
    path("informes/create", views.InformeCreateView.as_view(),
         name="informe-create"),
    path("informes/i/<int:pk>", views.InformeView.as_view(),
         name="informe"),
    path("informes/i/<int:pk>/update", views.InformeUpdateView.as_view(),
         name="informe-update"),
    path("informes/i/<int:pk>/delete",
         views.InformeDeleteView.as_view(),
         name="informe-delete"),
    ]

user_urls = [
    path("activity.png", views.UserActivityPlotView.as_view()),
    ]

urlpatterns = [
    path("", views.ColoniasList.as_view(), name="colonias"),
    path("rpc/", RPCEntryPoint.as_view(enable_doc=True), name="RPC"),
    path('colonia-add', views.ColoniaCreateView.as_view(), name="colonia-add"),
    path('colonia/c/<slug:colonia>', views.ColoniaView.as_view(),
         name="colonia"),
    path('colonia/c/<slug:colonia>/update', views.ColoniaUpdateView.as_view(),
         name="colonia-update"),
    path('colonia/c/<slug:colonia>/', include(colonia_urls)),
    path('user/u/<str:username>/profile', views.UserProfile.as_view(),
         name="user-activity"),
    path('comidas/<str:codigo>', views.CalendarioComidas.as_view(),
         name="calendario-comidas"),
    ]

gatos/models.py
from datetime import date, timedelta
from functools import reduce
from pathlib import Path
from PIL import Image
from PIL.ExifTags import TAGS
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.utils.text import slugify
from .data import vacunas
from .utils import pil_to_django_file, random_choice

SEXOS = [
          ("M", "Macho"),
          ("H", "Hembra")
]


class Alta:
    def __init__(self, gato):
        self.gato = gato

    @property
    def fecha(self):
        return self.gato.fecha_alta

    def get_absolute_url(self):
        return self.gato.get_absolute_url()

    def __str__(self):
        return f"Alta {self.gato.nombre}"

    def __repr__(self):
        return f"<{self.__class__.__name__} gato={self.gato.nombre}>"


class EstadoGato(models.TextChoices):
    LIBRE = 'LIBRE', 'Libre'
    CAPTURADO = 'CAPTURADO', 'Capturado'
    DESAPARECIDO = 'DESAPARECIDO', 'Desaparecido'
    OLVIDADO = 'OLVIDADO', 'Olvidado'
    MUERTO = 'MUERTO', 'Muerto'


# Ver https://docs.viewflow.io/fsm/models.html


class GatosColoniaManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(vecino=False)


class Gato(models.Model):
    slug = models.SlugField(max_length=200, unique=True, default="")
    nombre = models.CharField(max_length=200, unique=True)
    color = models.CharField(max_length=50)
    descripcion = models.TextField()
    colonia = models.ForeignKey("gatos.Colonia", on_delete=models.CASCADE,
                                related_name="gatos")
    retrato = models.ForeignKey("gatos.Foto", on_delete=models.SET_NULL,
                                null=True)
    sexo = models.CharField(max_length=10, choices=SEXOS)
    esterilizacion = models.DateField(null=True, blank=True)
    feo = models.BooleanField(default=False)
    vecino = models.BooleanField(default=False)
    nombre_vecino = models.CharField(max_length=200, blank=True)
    fecha_alta = models.DateField(auto_now=True)
    muerto = models.BooleanField(default=False)
    muerto_fecha = models.DateField(null=True, blank=True)
    estado = models.CharField(max_length=200, default="LIBRE")
    marcado = models.BooleanField(default=False)

    objects = models.Manager()
    gatos_colonia = GatosColoniaManager()

    class Meta:
        permissions = [
            ("morir_gato", ""),
            ]

    @property
    def peso(self):
        return self.get_ultima_captura().peso

    def get_vacunas(self):
        return Vacunacion.objects.filter(captura__gato=self)

    def get_peso(self):
        capturas = self.capturas.exclude(peso=None).order_by("-fecha_captura")
        if capturas:
            return capturas[0].peso
        return None

    def get_eventos(self, min_fecha=None, max_fecha=None):
        informes = self.informes
        fotos = self.fotos
        capturas = Captura.objects.filter(gato=self)
        vacunas = Vacunacion.objects.filter(captura__gato=self)
        diag = self.enfermedades
        avtos = self.avistamientos
        if min_fecha is not None:
            informes = informes.filter(fecha__gte=min_fecha)
            fotos = fotos.filter(fecha__gte=min_fecha)
            avtos = avtos.filter(fecha__gte=min_fecha)
            capturas = capturas.filter(fecha_captura__gte=min_fecha)
            vacunas = vacunas.filter(captura__fecha_captura__gte=min_fecha)
            diag = diag.filter(fecha_diagnostico__gte=min_fecha)
        if max_fecha is not None:
            informes = informes.filter(fecha__lte=max_fecha)
            fotos = fotos.filter(fecha__lte=max_fecha)
            avtos = avtos.filter(fecha__lte=max_fecha)
            capturas = capturas.filter(fecha_captura__lte=max_fecha)
            vacunas = vacunas.filter(captura__fecha_captura__lte=max_fecha)
            diag = diag.filter(fecha_diagnostico__lte=max_fecha)
        informes = list(informes.all())
        fotos = list(fotos.all())
        avtos = list(avtos.all())
        capturas = list(capturas.all())
        vacunas = list(vacunas.all())
        diag = list(diag.all())
        alta = [Alta(self)]
        return informes + fotos + alta + avtos + capturas + vacunas + diag

    def get_actividad(self, min_fecha=None, max_fecha=None):
        eventos = self.get_eventos(min_fecha=min_fecha, max_fecha=max_fecha)
        return [x.fecha for x in eventos]

    def toggle_avistamiento(self, fecha, user):
        avistamientos = self.avistamientos.filter(fecha=fecha)
        if avistamientos:
            avistamientos.delete()
        else:
            av = Avistamiento(colonia=self.colonia, gato=self,
                              usuario=user, fecha=date.today())
            av.save()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre)
        super().save(*args, **kwargs)

    @property
    def color_estado(self):
        if self.estado == "LIBRE":
            return "green"
        elif self.estado == "CAPTURADO":
            return "orange"
        elif self.estado == "DESAPARECIDO":
            return "lightgray"
        elif self.estado == "OLVIDADO":
            return "gray"
        elif self.estado == "MUERTO":
            return "black"
        else:
            return "pink"

    def get_absolute_url(self):
        return reverse("gato", kwargs={"colonia": self.colonia.slug,
                                       "gato": self.slug})

    def __str__(self):
        return self.nombre

    def __repr__(self):
        clase = self.__class__.__name__
        nombre = self.nombre
        colonia = self.colonia.nombre
        return f"<{clase} nombre={nombre} colonia='{colonia}'>"


class Colonia(models.Model):
    slug = models.SlugField(max_length=200, unique=True, default="")
    nombre = models.CharField(max_length=200)
    periodo_activo = models.DurationField(default=timedelta(120, 0, 0))
    descripcion = models.TextField(blank=True, default="")

    def get_eventos(self, min_fecha=None, max_fecha=None):
        informes = self.informes
        fotos = self.fotos
        altas = self.gatos
        avtos = self.avistamientos
        if min_fecha is not None:
            informes = informes.filter(fecha__gte=min_fecha)
            fotos = fotos.filter(fecha__gte=min_fecha)
            avtos = avtos.filter(fecha__gte=min_fecha)
            altas = altas.filter(fecha_alta__gte=min_fecha)
        if max_fecha is not None:
            informes = informes.filter(fecha__lte=max_fecha)
            fotos = fotos.filter(fecha__lte=max_fecha)
            avtos = avtos.filter(fecha__lte=max_fecha)
            altas = altas.filter(fecha_alta__lte=max_fecha)
        informes = list(informes.all())
        fotos = list(fotos.all())
        avtos = list(avtos.all())
        altas = [Alta(x) for x in altas.all()]
        return informes + fotos + avtos + altas

    def get_actividad(self, min_fecha=None, max_fecha=None):
        eventos = self.get_eventos(min_fecha=min_fecha, max_fecha=max_fecha)
        return [x.fecha for x in eventos]

    def get_gatos_activos(self, min_fecha=None, max_fecha=None):
        if min_fecha is None:
            min_fecha = date.today() - self.periodo_activo
        result = set()
        eventos = self.get_eventos(min_fecha=min_fecha, max_fecha=max_fecha)
        for evento in eventos:
            if hasattr(evento, "gatos"):
                for gato in evento.gatos.filter(muerto=False):
                    result.add(gato)
            if hasattr(evento, "gato"):
                result.add(evento.gato)
        return list(result)

    def get_gatos_desaparecidos(self):
        result = []
        activos = self.get_gatos_activos()
        for gato in self.gatos.filter(muerto=False):
            if gato not in activos:
                result.append(gato)
        return result

    def get_avistamientos(self, date):
        vistos_set = {av.gato for av in self.avistamientos.filter(fecha=date)}
        gatos = self.get_gatos_activos()
        vistos = [x for x in gatos if x in vistos_set]
        no_vistos = [x for x in gatos if x not in vistos_set]
        return vistos, no_vistos

    def get_gatos_muertos(self):
        return self.gatos.filter(muerto=True)

    def get_calendarios(self):
        return ""

    def toggle_comida(self, fecha, user):
        if not fecha > date.today():
            return
        comidas = self.comidas.filter(fecha=fecha).order_by('id')
        if not comidas:
            comida = AsignacionComida(fecha=fecha, usuario=user, colonia=self)
            comida.save()
        else:
            if comidas[0].usuario == user:
                comidas.delete()
            else:
                comidas[0].usuario = user
                comidas[0].save()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.nombre)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("colonia", kwargs={"colonia": self.slug})

    def __str__(self):
        return self.nombre

    def __repr__(self):
        return f"<{self.__class__.__name__} nombre='{self.nombre}'>"


class UserBound(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.SET_NULL,
                                blank=True,
                                null=True)
    nombre_usuario = models.CharField(max_length=200, blank=True, default="")

    def save(self, *args, **kwargs):
        if self.usuario is not None and self.nombre_usuario != "":
            self.nombre_usuario = " ".join((self.usuario.first_name,
                                            self.usuario.last_name))
        super().save(*args, **kwargs)

    class Meta:
        abstract = True


def foto_upload_to(instance, filename):
    path = Path(filename)
    ext = path.suffix
    return f"fotos/{instance.id}{ext}"


class Foto(UserBound):
    MINIATURA_SIZE = (170, 120)

gatos/templates/gatos/actividad_colonia.html
{% extends 'gatos/colonia_base.html' %}
{% block body %}
  <div class="column">
  <div class="main-subheader">
    <div class="subtitle">
      <h3>Actividad Reciente</h3>
    </div>
    <div class="actions">
     </div>
  </div>

{% include 'gatos/actividades-block.html' with agrupador=agrupador %}
{% endblock %}

gatos/templates/gatos/avistamientos.html
{% extends 'gatos/colonia_base.html' %}
{% load static %}

{% block head %}
  <script src="{% static 'js/jsonrpc.js' %}" charset="utf-8"></script>
{% endblock %}

{% block body %}
<div class="main-subheader">
  <div class="subtitle">
    <h2>Avistamientos de Hoy</h2>
  </div>
  <div class="actions">
  </div>
</div>

<div class="main-subheader">
  <div class="subtitle">
    <h3>Pendientes</h2>
  </div>
  <div class="actions">
    {% if perms.gatos.add_gato %}
      <a href="{% url 'gato-add' colonia=colonia.slug %}">Añadir Gato</a>
    {% endif %}
  </div>
</div>


<div class="galeria-gatos">
{% for gato in no_vistos %}
    <div class="enlace-gato">
      <div class="marco-foto">
      {% if gato.retrato.miniatura %}
        <img onclick="avistar_gato('{{ colonia.slug }}', '{{ gato.slug }}')" class="galeria-gatos-miniatura {% if gato.retrato.es_fea %} fea{% endif %}" src="{{ gato.retrato.miniatura.url }}">
    {% else %}
      <div onclick="avistar_gato('{{ colonia.slug }}', '{{ gato.slug }}')" class="galeria-gatos-no-miniatura">No hay foto</div>
    {% endif %}
      </div>
    {% if not gato.vecino %}
      <div class="enlace-gato-nombre">{{ gato.nombre }}</div>
    {% else %}
      <div class="enlace-gato-nombre">{{ gato.nombre }} de {{ gato.nombre_vecino }}</div>
    {% endif %}
    </div>
{% empty %}Se vieron todos los gatos{% endfor %}
</div>


<div class="main-subheader">
</div>
  <div class="subtitle">
    <h3>Vistos</h2>
  </div>
  <div class="actions">
  </div>
</div>

<div class="galeria-gatos">
{% for gato in vistos %}
    <div class="enlace-gato">
      <div class="marco-foto">
      {% if gato.retrato.miniatura %}
        <img onclick="avistar_gato('{{ colonia.slug }}', '{{ gato.slug }}')" class="galeria-gatos-miniatura {% if gato.retrato.es_fea %} fea{% endif %}" src="{{ gato.retrato.miniatura.url }}">
    {% else %}
      <div onclick="avistar_gato('{{ colonia.slug }}', '{{ gato.slug }}')" class="galeria-gatos-no-miniatura">No hay foto</div>
    {% endif %}
      </div>
    {% if not gato.vecino %}
      <div class="enlace-gato-nombre">{{ gato.nombre }}</div>
    {% else %}
      <div class="enlace-gato-nombre">{{ gato.nombre }} de {{ gato.nombre_vecino }}</div>
    {% endif %}
    </div>
{% empty %}No hay gatos vistos hoy{% endfor %}
</div>
<script charset="utf-8">

  const API_URL = "{% url 'RPC' %}";

</script>
{% endblock %}

gatos/templates/gatos/captura_confirm_delete.html
{% extends 'gatos/colonia_base.html' %}
{% block body %}
<div id="confirmacion-mensaje">
  ¿Está seguro de querer borrar la {{ captura }}?
</div>
<form method="POST">
  {% csrf_token %}
  <div class="confirmations">
  <input type="submit" value="Confirmar"/>
  </div>
</form>
{% endblock %}

gatos/templates/gatos/captura_view.html
{% extends 'gatos/gato_base.html' %}
{% load markdown %}
{% block gato_head %}
{% endblock %}

{% block gato_body %}
  <div class="main-subheader">
    <div class="subtitle">
    <p>Captura:</p>
    <h3>Fecha: {{ captura.fecha_captura }} Peso: {{ captura.peso }}</h3>
        </div>
        <div class="actions">
          {% if perms.gatos.change_captura and captura.capturado %}<a href="{% url 'captura-update' colonia=colonia.slug gato=gato.slug pk=captura.id %}">Editar</a> {% endif %} {% if perms.gatos.delete_captura %}<a href="{% url 'captura-delete' colonia=colonia.slug gato=gato.slug pk=captura.id %}">Borrar</a>{% endif %}
        </div>
  </div>

  <article>
  {{ captura.observaciones|render_markdown }}
  </article>
{% endblock %}

gatos/templates/gatos/colonia_new.html
{% extends 'base.html' %}
{% block base_head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.css">
<script src="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.js"></script>
{% endblock %}

{% block base_body %}
<div class="main-subheader">
  <div class="subtitle">
     <h2>Crear Colonia</h2>
  </div>
  <div class="actions"></div>
</div>

<form class="gatos-form" action="{% url 'colonia-add' %}" method="POST">
{{ form.as_div }}
{% csrf_token %}
<div class="buttons">
  <input type="submit" value="Guardar">
</div>
</form>

<script>
   const easyMDE = new EasyMDE();
</script>
{% endblock %}

gatos/templates/gatos/colonias.html
{% extends 'base.html' %}
{% block base_body %}
<div class="main-subheader">
  <div class="subtiltle">
    <h1>Colonias</h1>
  </div>
  <div class="actions">
    {% if perms.gatos.add_colonia %}
    <a href="{% url "colonia-add" %}">Añadir Colonia</a>
  {% endif %}
  </div>
</div>
<div id="colonias">
{% for colonia in object_list %}
  <div class="colonia"><a href="{{ colonia.get_absolute_url }}">{{ colonia.nombre }}</a></div>
{% empty %}
  No hay colonias
{% endfor %}
</div>
{% endblock %}

gatos/templates/gatos/custom_checkbox_select.html
{# templates/custom_checkbox_select.html #}
    {% for group, options, index in widget.optgroups %}
    <div class="galeria-gatos">
        {% for option in options %}
        <label class="foto-label" for="{{ widget.attrs.id }}_{{ index }}">
        <div class="marco-foto">
          {% if option.value.instance.retrato.miniatura %}
          <img class="galeria-fotos-miniatura{% if option.value.instance.feo %} fea{% endif %}" src="{{ option.value.instance.retrato.miniatura.url }}" alt="{{ option.label }}">
            {% else %}
            <div class="galeria-fotos-no-miniatura">No hay miniatura</div>
            {% endif %}
        </div>
        <input type="checkbox" name="{{ widget.name }}" value="{{ option.value }}" id="{{ widget.attrs.id }}_{{ index }}" {% if option.selected %}checked{% endif %}>{{ option.value.instance.nombre }}

        </label>
        {% endfor %}
    {% endfor %}
</ul>

gatos/templates/gatos/enfermedad_update_view.html
{% extends 'gatos/gato_form_base.html' %}
{% block form_body %}

<div class="main-subheader">
  <div class="subtitle">
    <h2>Editar Enfermedad</h2>
  </div>
  <div class="actions"></div>
</div>

<form class="gatos-form" action="{% url 'enfermedad-update' colonia=colonia.slug gato=gato.slug pk=enfermedad.id %}" method="POST">
{{ form.as_div }}
{% csrf_token %}
<div class="buttons">
  <input type="submit" value="Guardar"\>
</div>
</form>
{% endblock %}

gatos/templates/gatos/foto.html
{% extends 'gatos/colonia_base.html' %}
{% load l10n %}
{% block body %}
<div class="main-subheader">
  <div class="subtitle">
    <p>{{ foto.id }}</p>
    <h2>Foto del {{ foto.fecha|localize }}</h2>
  </div>
  <div class="actions">
    {% if perms.gatos.change_foto %}
    <a href="{% url 'foto-update' colonia=foto.colonia.slug foto=foto.id %}">Editar Foto</a>
    {% endif %}
    {% if perms.gatos.delete_foto %}
    <a href="{% url 'foto-delete' colonia=foto.colonia.slug foto=foto.id %}">Borrar Foto</a>
    {% endif %}
  </div>
</div>
{% if gatos %}
<h3>Gatos</h3>
{% include "gatos/gatos-block.html" with gatos=gatos %}
{% endif %}
<img class="foto" src="{{ foto.foto.url }}"/><br>
{% endblock %}

gatos/templates/gatos/gato_form_base.html
{% extends 'gatos/gato_base.html' %}
{% block gato_head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.css">
<script src="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.js"></script>

{% block form_head %}
{% endblock %}

{% endblock %}
{% block gato_body %}
{% block form_body %}
{% endblock %}

<script>
   const easyMDE = new EasyMDE();
</script>

{% endblock %}

gatos/templates/gatos/gato_update.html
{% extends 'gatos/colonia_form_base.html' %}
{% block form_body %}
<div class="main-subheader">
  <div class="subtitle">
	<h2>Editar Gato</h2>
  </div>
  <div class="actions"></div>
</div>
<form class="gatos-form" action="{% url 'gato-update' colonia=colonia.slug gato=gato.slug %}" method="POST">
{{ form.as_div }}
{% csrf_token %}
<div class="buttons">
<input type="submit" value="Guardar"\>
</div>
</form>
{% endblock %}

gatos/templates/gatos/informe.html
{% extends 'gatos/colonia_base.html' %}
{% load markdown %}
{% block head %}
{% endblock %}

{% block body %}
<div class="main-subheader">
  <div class="subtitle">
    <p>Informe:</p>
    <h2>{{ informe.titulo }}</h2>
  </div>
<div class="actions">
   {% if perms.gatos.change_informe %}
    <a href="{% url 'informe-update' colonia=colonia.slug pk=informe.id %}">Editar</a>
    {% endif %}
    {% if perms.gatos.delete_informe %}
    <a href="{% url 'informe-delete' colonia=colonia.slug pk=informe.id %}">Borrar</a>
    {% endif %}
  </div>
</div>

<article>
  {{ informe.texto|render_markdown }}
</article>

</div>
{% if gatos %}
<h3>Gatos</h3>
{% include "gatos/gatos-block.html" with gatos=gatos %}
{% endif %}

{% endblock %}

gatos/templates/gatos/informes.html
{% extends 'gatos/colonia_base.html' %}
{% load atleast %}
{% block body %}

<div class="main-subheader">
  <div class="subtitle">
    <h2>Informes</h2>
  </div>
  <div class="actions">
    {% if perms.gatos.add_informe %}
<a href="{% url 'informe-create' colonia=colonia.slug %}">Crear Informe</a>
    {% endif %}
   </div>
</div>

{% for mes, informes in agrupador %}
  <h3>{{ mes|date:"F Y"}}</h3>
<table class="tabla-informes">
  <tr><th>Nombre</th><th>Autor</th><th>Fecha</th><th>Acciones</th></tr>
{% for informe in informes|atleast:6 %}
{% if informe %}
  <tr>
    <td class="titulo"><a href="{% url 'informe' colonia=colonia.slug pk=informe.id %}">{{ informe.titulo }}</a></td>
    <td class="autor">{{ informe.usuario|default_if_none:"<sin nombre>" }}</td>
    <td class="fecha">{{ informe.fecha|date:'d/m/Y' }}</td>
    <td class="acciones"><a href="{% url 'informe-update' colonia=colonia.slug pk=informe.id %}">Editar</a> | <a href="{% url 'informe-delete' colonia=colonia.slug pk=informe.id %}">Borrar</a></td>
  </tr>
{% else %}
  <tr><td></td><td></td><td></td><td></td></tr>
{% endif %}
{% endfor %}
</table>
{% endfor %}
{% endblock %}

gatos/templates/gatos/mensaje.html
{% extends 'gatos/colonia_base.html' %}
{% block body %}
<div id="mensaje-cuerpo">
  {{ mensaje }}
</div>
<div id="mensaje-ok">
  {% if gato %}
    <a href="{{ gato.get_absolute_url }}">Ok</a>
  {% elif colonia %}
    <a href="{{ colonia.get_absolute_url }}">Ok</a>
  {% else %}
    <a href="{% url 'colonias' %}">Ok</a>
  {% endif %}
</div>
{% endblock %}